<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel' => 'Cancelar',
    'Categories' => 'Categorías',
    'Category activated successfully' => 'Categoría activada con éxito',
    'Category created successfully' => 'Categoría creada con éxito',
    'Category deactivated successfully' => 'Categoría desactivada con éxito',
    'Category not activated' => 'Categoría no activada',
    'Category not deactivated' => 'Categoría no desactivada',
    'Category not saved' => 'Categoría no guardada',
    'Category not updated' => 'Categoría no actualizada',
    'Category updated successfully' => 'Categoría actualizada exitosamente',
    'Create Category' => 'Crear categoría',
    'Description' => 'Descripción',
    'ID' => 'Id',
    'Name' => 'Nombre',
    'Reset' => 'Restablecer',
    'Save' => 'Guardar',
    'Search' => 'Buscar',
    'State' => 'Estado',
    'The requested page does not exist.' => 'La pagina solicitada no existe',
    'Update' => 'Actualizar',
    'Update Category: {name}' => 'Actualizar Categoría: {name}',
    'Category not deactivated.' => 'Categoría no desactivada',
];
