<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create Deposit' => 'Crear ingreso',
    'Date Hour' => 'Fecha Hora',
    'Deposit activated successfully' => 'Ingreso activado con éxito',
    'Deposit created successfully' => 'Ingreso creado con éxito',
    'Deposit deactivated successfully' => 'Ingreso desactivado con éxito',
    'Deposit not activated' => 'Ingreso no activado',
    'Deposit not deactivated' => 'Ingreso no desactivaod',
    'Deposit not saved' => 'Ingreso no guardado',
    'Deposits' => 'Ingresos',
    'Number' => 'Numero',
    'Reset' => 'Restablecer',
    'Search' => 'Buscar',
    'See' => 'Ver',
    'See Deposit: {name}' => 'Ver ingreso: {name}',
    'State' => 'Estado',
    'Supplier ID' => 'Proveedor',
    'The requested page does not exist.' => 'La pagina solicitada no existe',
    'Total Purchase' => 'Total Compra',
    'User ID' => 'Usuario',
    'Voucher Type ID' => 'Comprobante'
];
