<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel' => 'Cancelar',
    'Category ID' => 'Categoria',
    'Code' => 'Codigo',
    'Create Item' => 'Crear articulo',
    'Description' => 'Descripcion',
    'Image' => 'Imagen',
    'Item activated successfully.' => 'Articulo activado con éxito',
    'Item created successfully.' => 'Articulo creado con éxito',
    'Item deactivated successfully.' => 'Articulo desactivado con éxito',
    'Item not activated.' => 'Articulo no activado',
    'Item not deactivated.' => 'Articulo no desactivado',
    'Item not saved.' => 'Articulo no guardado',
    'Item not updated.' => 'Articulo no actualizado',
    'Item updated successfully.' => 'Articulo actualizado con éxito',
    'Items' => 'Articulos',
    'Name' => 'Nombre',
    'Reset' => 'Restablecer',
    'Save' => 'Guardar',
    'Search' => 'Buscar',
    'State' => 'Estado',
    'Stock' => 'Stock',
    'Update' => 'Actualizar',
    'Update Item: {name}' => 'Actualizar articulo: {name}',
    'The requested page does not exist.' => 'La pagina solicitada no existe',
];
