<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Dirección',
    'Cancel' => 'Cancelar',
    'Create Person' => 'Crear Persona',
    'Document Number' => 'Numero Documento',
    'Document Type ID' => 'Tipo Documento',
    'Mail' => 'Correo',
    'Name' => 'Nombre',
    'Person Type ID' => 'Tipo Persona',
    'Person activated successfully' => 'Persona activada con éxito',
    'Person created successfully' => 'Persona creada con éxito',
    'Person deactivated successfully' => 'Persona desactivada con éxito',
    'Person not activated' => 'Persona no activada',
    'Person not deactivated' => 'Persona no desactivada',
    'Person not saved' => 'Persona no guardada',
    'Person not updated' => 'Persona no actualizada',
    'Person updated successfully' => 'Persona actualizada con éxito',
    'Persons' => 'Personas',
    'Phone' => 'Telefono',
    'Picture' => 'Imagen',
    'Reset' => 'Restablecer',
    'Save' => 'Guardar',
    'Search' => 'Buscar',
    'State' => 'Estado',
    'The requested page does not exist.' => 'La pagina solicitada no existe',
    'Update' => 'Actualizar',
    'Update Person: {name}' => 'Actualizar persona: {name}',
];
