<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Client ID' => 'Cliente',
    'Create Sale' => 'Crear Venta',
    'Date Hour' => 'Fecha Hora',
    'Reset' => 'Restablecer',
    'Sale activated successfully' => 'Venta activada existosamente',
    'Sale created succesfully' => 'Venta creada existosamente',
    'Sale deactivated successfully' => 'Venta desactivada exitosamente',
    'Sale not activated' => 'Venta no activada',
    'Sale not deactivated' => 'Venta no desactivada',
    'Sale not saved' => 'Venta no guardada',
    'Sales' => 'Ventas',
    'Search' => 'Buscar',
    'State' => 'Estado',
    'Tax' => 'Impuesto',
    'The requested page does not exist.' => 'La pagina solicitada no existe',
    'Total Sale' => 'Total Venta',
    'Update' => 'Actualizar',
    'User ID' => 'Usuario',
    'View Sale: {name}' => 'Ver Venta: {name}',
    'Voucher Type ID' => 'Comprobante',
    'Voucher Sequence' => 'Serie Comprobante',
    'Voucher Number' => 'Numero Comprobante',
];
